# =============================================================================
# Transaction Service — Container profil (docker-compose / OpenShift)
# =============================================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}

# Account Service URL — konténer hálózaton a service nevével
quarkus.rest-client.account-service-api.url=${ACCOUNT_SERVICE_URL:http://account-service:8082}

quarkus.log.console.json.enabled=true
