# =============================================================================
# Customer Service — Dev profil (lokális fejlesztés, quarkus dev)
# =============================================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=demo
quarkus.datasource.password=demo
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_demo

# JSON logolás kikapcsolva dev módban (olvashatóbb)
quarkus.log.console.json.enabled=false
