# =============================================================================
# Customer Service — Container profil (docker-compose / OpenShift)
# =============================================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}

# JSON logolás bekapcsolva (log aggregátor számára)
quarkus.log.console.json.enabled=true
