apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: tamicsko-dev
data:
  DB_HOST: postgres
  DB_NAME: quarkus_demo
  CUSTOMER_SERVICE_URL: "http://customer-service:8081"
  ACCOUNT_SERVICE_URL: "http://account-service:8082"
  TRANSACTION_SERVICE_URL: "http://transaction-service:8083"
