apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: tamicsko-dev
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: quarkus_demo
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "bankadmin", "-d", "quarkus_demo"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "bankadmin", "-d", "quarkus_demo"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tamicsko-dev
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: tamicsko-dev
data:
  init.sql: |
    CREATE SCHEMA IF NOT EXISTS customer_svc;
    CREATE SCHEMA IF NOT EXISTS account_svc;
    CREATE SCHEMA IF NOT EXISTS tx_svc;
    GRANT ALL ON SCHEMA customer_svc TO bankadmin;
    GRANT ALL ON SCHEMA account_svc TO bankadmin;
    GRANT ALL ON SCHEMA tx_svc TO bankadmin;
