# =============================================================================
# Account Service — Container profil (docker-compose / OpenShift)
# =============================================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}

quarkus.log.console.json.enabled=true
