# =============================================================================
# Backend (BFF) — Container profil (docker-compose / OpenShift)
# =============================================================================

# Service URL-ek — konténer hálózaton a service nevével
quarkus.rest-client.customer-service-api.url=${CUSTOMER_SERVICE_URL:http://customer-service:8081}
quarkus.rest-client.account-service-api.url=${ACCOUNT_SERVICE_URL:http://account-service:8082}
quarkus.rest-client.transaction-service-api.url=${TRANSACTION_SERVICE_URL:http://transaction-service:8083}

quarkus.log.console.json.enabled=true
